import type { Metadata } from "next"
import { Inter } from "next/font/google"

import TRPCProvider from "./_trpc/Provider"
import "./globals.css"
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react"

import Header from "@/components/Header"
import { ToastProvider } from "@/components/provider/toaster-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <TRPCProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={inter.className}>
            <ToastProvider />
            <div className="h-full">{children}</div>
          </body>
        </html>
      </TRPCProvider>
    </SessionProvider>
  )
}
